imports:
    - { resource: config_dev.yml }

services:
    app.map.google_maps_static_provider:
        class: 'Tests\AppBundle\Test\Map\DummyStaticMapProvider'

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

    old_sound_rabbit_mq.mailer_campaign_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.mailer_transactional_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.deputy_message_dispatcher_producer:
        class: 'Tests\AppBundle\Test\Producer\DeputyMessageNullProducer'

    Tests\AppBundle\Consumer\DummyConsumer: ~

    Tests\AppBundle\Test\Payment\PayboxProvider:
        arguments:
            - '%env(SSL_PRIVATE_KEY)%'

parameters:
    env(DATABASE_NAME): "enmarche_test"
    env(RECAPTCHA_PUBLIC_KEY): 'TEST_RECAPTCHA_PUBLIC_KEY'
    env(GMAPS_API_KEY):
    app_host: "test.%env(APP_HOST)%"
    amp_host: "test.%env(AMP_HOST)%"
    legislatives_host: "test.legislatives.%app_host%"
